# We use a minimal image, as we install Python from conda
language:
 - c

compiler:
  - gcc

# We are going to undo the shallow clone as the first step, so just clone it at
# depth 1.
git:
  depth: 1

# Don't do CI for WIP branches
branches:
  except:
    - /^WIP-.*$/
    - /^legacy$/

sudo: false
addons:
  apt:
    packages:
    - realpath
    - libsdl-dev

before_install:
  - .travis/setup-git.sh

install:
  - .travis/conda/setup.sh

script:
  - . .travis/conda/enter.sh
  - python setup.py test
  - python setup.py install
  - python setup.py pep8
